steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA']
# SSH into the VM instance and start the container
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'root@my-instance-vm'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    sudo docker pull gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA
    sudo docker run -d -p 8080:8080 gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA &
images:
- 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA'

